const Notification = require('../modules/notifications/model');

const minutesAgo = (minutes) => new Date(Date.now() - minutes * 60 * 1000);
const daysAgoAt = (days, hours, minutes) => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  date.setHours(hours, minutes, 0, 0);
  return date;
};
const fixedDate = (year, monthIndex, day, hours = 9, minutes = 0) =>
  new Date(year, monthIndex, day, hours, minutes, 0, 0);

const seedNotifications = async () => {
  try {
    const notificationsToSeed = [
      {
        title: 'Updated Return & Refund Policy',
        message: 'Our return window has been extended from 14 to 30 days effective July 1, 2026.',
        category: 'announcements',
        priority: 'medium',
        isRead: false,
        branchName: 'Store Manager',
        source: 'Saman Ratnayake',
        createdAt: fixedDate(2026, 5, 10, 9, 0),
        metadata: {
          seedKey: 'announcement-return-refund-policy-2026',
          announcementType: 'Policy',
          authorName: 'Saman Ratnayake',
          authorRole: 'Store Manager',
          isPinned: true,
          isSaved: false,
        },
      },
      {
        title: 'Mid-Year Sale - June 20 to June 30',
        message: 'Storewide 15-40% discounts. All POS terminals will auto-apply promo codes.',
        category: 'announcements',
        priority: 'high',
        isRead: false,
        branchName: 'Head Office',
        source: 'Administrator',
        createdAt: fixedDate(2026, 5, 9, 9, 0),
        metadata: {
          seedKey: 'announcement-mid-year-sale-2026',
          announcementType: 'Promotion',
          authorName: 'Administrator',
          authorRole: 'Head Office',
          expiresIn: '10 days',
          isPinned: false,
          isSaved: true,
        },
      },
      {
        title: 'Mandatory POS v3.2 Training Session',
        message: 'All cashiers must attend a 1-hour training session for the upcoming POS upgrade.',
        category: 'announcements',
        priority: 'medium',
        isRead: false,
        branchName: 'Training Coordinator',
        source: 'Kamal Perera',
        createdAt: fixedDate(2026, 5, 8, 9, 0),
        metadata: {
          seedKey: 'announcement-pos-v3-2-training',
          announcementType: 'Training',
          authorName: 'Kamal Perera',
          authorRole: 'Training Coordinator',
          expiresIn: '5 days',
          isPinned: false,
          isSaved: false,
        },
      },
      {
        title: 'System Updated to v3.1.5',
        message: 'Bug fixes for barcode scanning, faster checkout, and improved receipt printing.',
        category: 'announcements',
        priority: 'low',
        isRead: true,
        branchName: 'Technical Team',
        source: 'IT Department',
        createdAt: fixedDate(2026, 5, 5, 9, 0),
        metadata: {
          seedKey: 'announcement-system-updated-v3-1-5',
          announcementType: 'Update',
          authorName: 'IT Department',
          authorRole: 'Technical Team',
          isPinned: false,
          isSaved: true,
        },
      },
      {
        title: 'Staff Appreciation Day - June 28',
        message: 'Annual staff appreciation event. Venue: Skyline Ballroom. 6 PM start.',
        category: 'announcements',
        priority: 'low',
        isRead: true,
        branchName: 'Human Resources',
        source: 'HR Department',
        createdAt: fixedDate(2026, 5, 3, 9, 0),
        metadata: {
          seedKey: 'announcement-staff-appreciation-day-2026',
          announcementType: 'Event',
          authorName: 'HR Department',
          authorRole: 'Human Resources',
          expiresIn: '18 days',
          isPinned: false,
          isSaved: false,
        },
      },
      {
        title: 'Connection Pool Exhausted',
        message: 'The database connection pool has reached its maximum limit of 50 connections. Queries are being queued.',
        category: 'system',
        priority: 'high',
        isRead: false,
        branchName: 'Main Branch HQ',
        source: 'Database Monitor',
        createdAt: daysAgoAt(0, 10, 6),
        metadata: {
          seedKey: 'system-connection-pool-exhausted',
          systemStatus: 'error',
          component: 'database',
        },
      },
      {
        title: 'High CPU Usage Detected',
        message: 'Server CPU is at 87% utilization for the past 5 minutes. Performance may be degraded.',
        category: 'system',
        priority: 'medium',
        isRead: false,
        branchName: 'Main Branch HQ',
        source: 'Infrastructure Monitor',
        createdAt: daysAgoAt(0, 9, 55),
        metadata: {
          seedKey: 'system-high-cpu-usage-detected',
          systemStatus: 'warning',
          component: 'application-server',
        },
      },
      {
        title: 'Automated Backup Completed',
        message: 'Daily database backup successfully completed and verified. Stored to offsite replica.',
        category: 'system',
        priority: 'low',
        isRead: true,
        branchName: 'Main Branch HQ',
        source: 'Backup Service',
        createdAt: daysAgoAt(0, 9, 30),
        metadata: {
          seedKey: 'system-automated-backup-completed',
          systemStatus: 'success',
          component: 'backup',
        },
      },
      {
        title: 'Network Switch Restarted',
        message: 'Managed switch at rack B was restarted remotely for firmware update. Brief 30s downtime.',
        category: 'system',
        priority: 'low',
        isRead: true,
        branchName: 'Downtown Store',
        source: 'Network Operations',
        createdAt: daysAgoAt(0, 9, 18),
        metadata: {
          seedKey: 'system-network-switch-restarted',
          systemStatus: 'info',
          component: 'network',
        },
      },
      {
        title: 'API Error Rate Elevated',
        message: 'Checkout API error rate crossed 3% during the last monitoring window. Investigation started.',
        category: 'system',
        priority: 'high',
        isRead: false,
        branchName: 'Main Branch HQ',
        source: 'API Monitor',
        createdAt: daysAgoAt(0, 9, 5),
        metadata: {
          seedKey: 'system-api-error-rate-elevated',
          systemStatus: 'error',
          component: 'api',
        },
      },
      {
        title: 'Disk Usage Threshold Reached',
        message: 'Reports storage volume is at 78% capacity. Archive cleanup is recommended this week.',
        category: 'system',
        priority: 'medium',
        isRead: false,
        branchName: 'Main Branch HQ',
        source: 'Storage Monitor',
        createdAt: daysAgoAt(0, 8, 48),
        metadata: {
          seedKey: 'system-disk-usage-threshold-reached',
          systemStatus: 'warning',
          component: 'storage',
        },
      },
      {
        title: 'Security Rules Synced',
        message: 'Role and permission cache refreshed successfully across all active application nodes.',
        category: 'system',
        priority: 'low',
        isRead: true,
        branchName: 'Main Branch HQ',
        source: 'Identity Service',
        createdAt: daysAgoAt(0, 8, 30),
        metadata: {
          seedKey: 'system-security-rules-synced',
          systemStatus: 'success',
          component: 'identity',
        },
      },
      {
        title: 'Created new order - #ORD-2847',
        message: '3 items - $124.50',
        category: 'activity',
        priority: 'low',
        isRead: true,
        branchName: 'Downtown Store',
        source: 'POS Billing',
        createdAt: daysAgoAt(0, 9, 30),
        metadata: {
          seedKey: 'activity-created-order-ord-2847',
          activityType: 'orders',
          actorName: 'Amali Fernando',
          actorRole: 'Customer',
          actorTone: 'bg-pink-100 text-pink-700',
          orderId: 'ORD-2847',
        },
      },
      {
        title: 'Updated stock - USB-C Cables (SKU-2241)',
        message: '+50 units added',
        category: 'activity',
        priority: 'low',
        isRead: true,
        branchName: 'Downtown Store',
        source: 'Inventory Management',
        createdAt: daysAgoAt(0, 9, 20),
        metadata: {
          seedKey: 'activity-updated-stock-usb-c-cables',
          activityType: 'inventory',
          actorName: 'Nimal Liyanage',
          actorRole: 'Stock Manager',
          actorTone: 'bg-indigo-100 text-indigo-700',
          sku: 'SKU-2241',
        },
      },
      {
        title: 'Processed payment - Order #ORD-2843',
        message: 'Visa ****4821 - $89.00',
        category: 'activity',
        priority: 'low',
        isRead: true,
        branchName: 'Downtown Store',
        source: 'Payment Processing',
        createdAt: daysAgoAt(0, 9, 15),
        metadata: {
          seedKey: 'activity-processed-payment-ord-2843',
          activityType: 'payments',
          actorName: 'Amali Fernando',
          actorRole: 'Customer',
          actorTone: 'bg-pink-100 text-pink-700',
          orderId: 'ORD-2843',
        },
      },
      {
        title: 'Daily backup completed - Database',
        message: 'Size: 284 MB - Duration: 42s',
        category: 'activity',
        priority: 'low',
        isRead: true,
        branchName: 'Main Branch HQ',
        source: 'System',
        createdAt: daysAgoAt(1, 17, 45),
        metadata: {
          seedKey: 'activity-daily-backup-database',
          activityType: 'system',
          actorName: 'System',
          actorRole: 'Auto',
          actorTone: 'bg-slate-200 text-slate-700',
        },
      },
      {
        title: 'Removed expired items - Perishable Goods',
        message: '12 items removed',
        category: 'activity',
        priority: 'low',
        isRead: true,
        branchName: 'Downtown Store',
        source: 'Inventory Management',
        createdAt: daysAgoAt(1, 17, 15),
        metadata: {
          seedKey: 'activity-removed-expired-items-perishable-goods',
          activityType: 'inventory',
          actorName: 'Kamal Perera',
          actorRole: 'Employee',
          actorTone: 'bg-emerald-100 text-emerald-700',
        },
      },
      {
        title: 'Low Stock: Wireless Headphones',
        message: 'SKU-1029 has only 2 units left. Reorder point is 10 units. Immediate action required.',
        category: 'alerts',
        priority: 'high',
        isRead: false,
        branchName: 'Downtown Store',
        source: 'Inventory Management',
        createdAt: minutesAgo(0),
        metadata: { seedKey: 'alert-low-stock-wireless-headphones', sku: 'SKU-1029' },
      },
      {
        title: 'Order Pending Review',
        message: 'Order #ORD-2836 has been pending approval for over 30 minutes. Awaiting manager sign-off.',
        category: 'alerts',
        priority: 'medium',
        isRead: false,
        branchName: 'Downtown Store',
        source: 'Purchase Orders',
        createdAt: minutesAgo(3),
        metadata: { seedKey: 'alert-order-pending-review-ord-2836', orderId: 'ORD-2836' },
      },
      {
        title: 'New Bulk Order Received',
        message: 'Corporate order #ORD-2847 received from Acme Corp. 32 items, total $4,280.00.',
        category: 'alerts',
        priority: 'low',
        isRead: false,
        branchName: 'Downtown Store',
        source: 'POS Billing',
        createdAt: minutesAgo(27),
        metadata: { seedKey: 'alert-bulk-order-acme-ord-2847', orderId: 'ORD-2847' },
      },
      {
        title: 'Scheduled Maintenance',
        message: 'System maintenance is planned for tonight 11 PM - 1 AM. Expect brief downtime.',
        category: 'alerts',
        priority: 'low',
        isRead: true,
        branchName: 'Main Branch HQ',
        source: 'System Admin',
        createdAt: minutesAgo(60),
        metadata: { seedKey: 'alert-scheduled-maintenance-tonight' },
      },
      {
        title: 'New Order received',
        message: 'Order #ORD-2847 has been placed by Walk-in Customer. Total: $124.50',
        category: 'orders',
        priority: 'high',
        isRead: false,
        branchName: 'Downtown Store',
        source: 'POS Billing',
        createdAt: minutesAgo(2),
        metadata: { seedKey: 'new-order-ord-2847', orderId: 'ORD-2847' },
      },
      {
        title: 'Low Stock Warning',
        message: "Item 'Wireless Mouse (SKU-4821)' is below reorder threshold. Only 3 units remaining.",
        category: 'inventory',
        priority: 'high',
        isRead: false,
        branchName: 'Downtown Store',
        source: 'Inventory Management',
        createdAt: minutesAgo(8),
        metadata: { seedKey: 'low-stock-sku-4821', sku: 'SKU-4821' },
      },
      {
        title: 'Payment Declined',
        message: 'Transaction #TXN-9923 was declined. Card ending in 4821 - please follow up.',
        category: 'alerts',
        priority: 'high',
        isRead: false,
        branchName: 'Downtown Store',
        source: 'Payment Processing',
        createdAt: minutesAgo(35),
        metadata: { seedKey: 'payment-declined-txn-9923', transactionId: 'TXN-9923' },
      },
      {
        title: 'Supplier Delivery Delayed',
        message: 'Expected delivery PO-1182 is delayed by 2 hours. Update replenishment schedule if needed.',
        category: 'alerts',
        priority: 'medium',
        isRead: false,
        branchName: 'Downtown Store',
        source: 'Supplier Management',
        createdAt: minutesAgo(42),
        metadata: { seedKey: 'alert-supplier-delivery-delayed-po-1182', purchaseOrderId: 'PO-1182' },
      },
      {
        title: 'Cash Drawer Variance',
        message: 'Register 03 cash count is $18.75 above expected total. Manager verification required.',
        category: 'alerts',
        priority: 'medium',
        isRead: false,
        branchName: 'Downtown Store',
        source: 'POS Billing',
        createdAt: minutesAgo(52),
        metadata: { seedKey: 'alert-cash-drawer-variance-register-03', registerId: 'REG-03' },
      },
      {
        title: 'Daily Sales Target Reached',
        message: 'Congratulations! The store has achieved 85% of the daily sales target.',
        category: 'activity',
        priority: 'low',
        isRead: true,
        branchName: 'Downtown Store',
        source: 'Business Analytics',
        createdAt: minutesAgo(60),
        metadata: {
          seedKey: 'daily-sales-target-85',
          activityType: 'system',
          actorName: 'RetailSync',
          actorRole: 'Analytics',
          actorTone: 'bg-blue-100 text-blue-700',
        },
      },
      {
        title: 'Manager Note',
        message: 'Reminder: Monthly inventory audit is scheduled for this Friday at 5 PM.',
        category: 'activity',
        priority: 'medium',
        isRead: true,
        branchName: 'Main Branch HQ',
        source: 'System Admin',
        createdAt: minutesAgo(180),
        metadata: {
          seedKey: 'manager-note-monthly-audit',
          activityType: 'system',
          actorName: 'System Admin',
          actorRole: 'Admin',
          actorTone: 'bg-slate-200 text-slate-700',
        },
      },
    ];

    console.log('Seeding notifications...');

    for (const notificationData of notificationsToSeed) {
      const seedKey = notificationData.metadata.seedKey;
      const existingNotification = await Notification.findOne({ 'metadata.seedKey': seedKey });

      if (!existingNotification) {
        await Notification.create(notificationData);
        console.log(`Created notification: ${notificationData.title}`);
      } else {
        await Notification.updateOne(
          { _id: existingNotification._id },
          {
            $set: {
              ...notificationData,
              updatedAt: new Date(),
            },
          }
        );
        console.log(`Updated notification: ${notificationData.title}`);
      }
    }

    console.log('Notification seeding completed successfully.');
  } catch (error) {
    console.error('Error seeding notifications:', error);
    throw error;
  }
};

module.exports = seedNotifications;
